### ISSUE TITLE
Images being sent as a link

### ISSUE THREAD

**Issue by tjaderxyz** [mautrix/googlechat#47]
When someone on Hangouts sends me an image I'm getting a 
https://chat.google.com/api/get_hangouts_attachment_url link instead of the image itself.

**Comment by swmarks** [comment]
You can thank Google for this one. This means your chat partner is using Google Chat now instead of Hangouts Classic. I doubt anyone will bother spending time trying to work around this when Google is going to kill Hangouts soon anyway.

**Comment by sep76** [comment]
Sometimes there is not a link either. just text that alludes to a link.


```
I shared "20210803_231645.jpg" using the new Google Chat.
Click here to view.
```

**Comment by sep76** [comment]
will mautrix/hangouts support google chat in the future? or is it so different there will need to be developed a new bridge ?

**Comment by mochman** [comment]
> 
> 
> will mautrix/hangouts support google chat in the future? or is it so different there will need to be developed a new bridge ?

Hopefully, beeperhq.com is [offering some cash](https://matrix.org/blog/2021/01/22/this-week-in-matrix-2021-01-22) for people to develop a google chat bridge.
