### ISSUE TITLE
Failed to find form '#gaia_loginform' in page

### ISSUE THREAD

**Issue by RangerMauve** [mautrix/googlechat#50]
Getting the error `Login failed: Failed to find form '#gaia_loginform' in page` after submitting the password to the login form.

Trying to follow the manual steps, I'm not seeing the oauth_code cookie in any of the accounts.google.com requests.

**Comment by tulir** [comment]
That first error isn't possible on an up to date bridge (automatic login was removed entirely). `oauth_code` appears after you sign in and reach the spinner. It'll also be in the browser storage, not necessarily any of the requests (except maybe the last response or something)

**Comment by RangerMauve** [comment]
Thank you for checking!

I looked again and my issue was that I was using the incorrect login page. 😅
