### ISSUE TITLE
Double Puppeting not working

### ISSUE THREAD

**Issue by Kevin8675** [mautrix/googlechat#56]
I am trying to enable double puppeting and double puppeting does work with other bridges (mx-puppet-discord). I have set it up the Shared Secret Authenticator for synapse and I have put the shared secret into the config.yaml but when I try any of the -matrix commands such as ping-matrix the bot just replies with "This bridge has not implemented the ping-matrix command." login-matrix has the same error. Can anyone help?

**Comment by tulir** [comment]
It should work fine even without those commands

**Comment by Kevin8675** [comment]
> It should work fine even without those commands

How can I check if it is working?

**Comment by Kevin8675** [comment]
So I just sent a message from google chat with the user that I linked in matrix. In the log I can see this error:

`[2021-11-26 16:34:54,884] [WARNING@mau.portal.dm:18wU7gAAAAE-117032971095616605580] Ignoring own message Sl5vj-0RGUw in private chat because own puppet is not in room.`

**Comment by tulir** [comment]
The bridge should log a warning when starting the bridge if automatically enabling double puppeting fails

**Comment by Kevin8675** [comment]
> The bridge should log a warning when starting the bridge if automatically enabling double puppeting fails

I just restarted the bridge and I got this in the log:
```
[2021-11-26 16:55:45,629] [ERROR@mau.user.@kevin:matrix.dwbi.ca] Failed to automatically enable custom puppet
Traceback (most recent call last):
  File "/home/pi/gchat/lib/python3.9/site-packages/mautrix_googlechat/user.py", line 297, in on_connect_later
    await puppet.switch_mxid(access_token="auto", mxid=self.mxid)
  File "/home/pi/gchat/lib/python3.9/site-packages/mautrix/bridge/custom_puppet.py", line 181, in switch_mxid
    access_token = await self._login_with_shared_secret(mxid)
  File "/home/pi/gchat/lib/python3.9/site-packages/mautrix/bridge/custom_puppet.py", line 166, in _login_with_shared_secret
    raise AutologinError(f"Didn't get an access token: {error_msg}") from None
mautrix.bridge.custom_puppet.AutologinError: Didn't get an access token: Invalid password
```

**Comment by tulir** [comment]
That sounds like the shared secret in the config isn't correct

**Comment by Kevin8675** [comment]
> That sounds like the shared secret in the config isn't correct (or the synapse module is set up incorrectly, the latest version breaks stuff)

I was able to fix it by enabling the "m_login_password_support_enabled" in the module section in homeserver.yaml. You should probably put this somewhere in the docs for dubble puppeting. Thanks for the help!
