### ISSUE TITLE
[RFE] Inform GChat users that they are talking to a bridged account

### ISSUE THREAD

**Issue by bookwar** [mautrix/googlechat#58]
We'd like to make it more visible to the users of the GChat that they are talking to someone connected to GChat over the Matrix Bridge

Are there any options to mark account "bridged" on the GChat side, for example set a custom status message for the "puppet"?

**Comment by tulir** [comment]
No, I don't think GChat supports anything like that. Bot accounts could technically be used and would be labeled as bots, but I think Google Chat's bot API is far too limited for proper bridging (would need unrestricted sending and receiving all messages in the chats the bot is added to).
