### ISSUE TITLE
Invalid URL: host is required for absolute urls

### ISSUE THREAD

**Issue by arcnmx** [mautrix/googlechat#68]
Attempting to use a config like:

```yaml
appservice:
  database: postgres://mautrix-googlechat@/mautrix_googlechat
```

Now results in the following failure:

```
mautrix-googlechat[685955]:   File "/lib/python3.9/site-packages/mautrix/bridge/bridge.py", line 168, in prepare_db
mautrix-googlechat[685955]:     self.db = Database.create(
mautrix-googlechat[685955]:   File "/lib/python3.9/site-packages/mautrix/util/async_db/database.py", line 66, in create
mautrix-googlechat[685955]:     url = URL(url)
mautrix-googlechat[685955]:   File "/lib/python3.9/site-packages/yarl/_url.py", line 167, in __new__
mautrix-googlechat[685955]:     raise ValueError("Invalid URL: host is required for absolute urls")
```

Previously (on bafd1f7e0a016d7a68adaae833d87b10990ea6f3 with mautrix-python 0.14) this worked as expected. As far as I know, using an empty host is the only/standard way to indicate connection via local unix socket path rather than connecting over tcp, so I'm not sure what alternatives are meant to be used here?

This can be worked around by finding the actual socket path, and uri-encoding it into the host like `postgres://mautrix-googlechat@%2Frun%2Fpostgresql/mautrix_googlechat`

(this may actually be a [mautrix-python](https://github.com/mautrix/python) issue, I'm not sure, should it be moved?)

**Comment by tulir** [comment]
Usually `postgres:///mautrix_googlechat` is enough. If you absolutely need a custom username, it might work with a `?user` query parameter.

**Comment by arcnmx** [comment]
Fair, the username is only really there for consistency. The assumption by the error message seems false though? I didn't even try `postgres:///x` because the error message implies that it too would be invalid (given that it's absolute without a host). Maybe that also makes it a yarl issue, afaik a missing host can still be valid even with authority.

**Comment by Sodykhorn** [comment]
> Attempting to use a config like:
> 
> 
> 
> ```yaml
> 
> appservice:
> 
>   database: postgres://mautrix-googlechat@/mautrix_googlechat
> 
> ```
> 
> 
> 
> Now results in the following failure:
> 
> 
> 
> ```
> 
> mautrix-googlechat[685955]:   File "/lib/python3.9/site-packages/mautrix/bridge/bridge.py", line 168, in prepare_db
> 
> mautrix-googlechat[685955]:     self.db = Database.create(
> 
> mautrix-googlechat[685955]:   File "/lib/python3.9/site-packages/mautrix/util/async_db/database.py", line 66, in create
> 
> mautrix-googlechat[685955]:     url = URL(url)
> 
> mautrix-googlechat[685955]:   File "/lib/python3.9/site-packages/yarl/_url.py", line 167, in __new__
> 
> mautrix-googlechat[685955]:     raise ValueError("Invalid URL: host is required for absolute urls")
> 
> ```
> 
> 
> 
> Previously (on bafd1f7e0a016d7a68adaae833d87b10990ea6f3 with mautrix-python 0.14) this worked as expected. As far as I know, using an empty host is the only/standard way to indicate connection via local unix socket path rather than connecting over tcp, so I'm not sure what alternatives are meant to be used here?
> 
> 
> 
> This can be worked around by finding the actual socket path, and uri-encoding it into the host like `postgres://mautrix-googlechat@%2Frun%2Fpostgresql/mautrix_googlechat`
> 
> 
> 
> (this may actually be a [mautrix-python](https://github.com/mautrix/python) issue, I'm not sure, should it be moved?)

I'm so sorry
