### ISSUE TITLE
Quoting text is broken

### ISSUE THREAD

**Issue by nolimbsdotdev** [mautrix/googlechat#71]
Replying to a previous message results in a quote of that message appearing in the senders chat window. However, the receiver just sees the sender's new message, without the context provided by the quoted message. This leads to significant misunderstandings in Google chat conversations. 

Could the bridge be modified to prepend the senders message with the quote for context? e.g. the receiver might see:

BOB SAID: "this was bob's message"
This is senders reply.

Thanks.

**Comment by tulir** [comment]
Probably not going to do this, just don't use replies.

**Comment by nolimbsdotdev** [comment]
But maybe the bot should leave a warning that replies are not supported when the user tries? Since matrix clients support replies, the user will assume the bridge will too, unless informed otherwise.
