### ISSUE TITLE
Enhancement: Thread Support for Google Chat

### ISSUE THREAD

**Issue by itguyeric** [mautrix/googlechat#72]
Currently, threads from Google Spaces show up in Matrix as replies.

I would like a feature to make Matrix threads to be able to talk to Google Chat threads.

![image](https://user-images.githubusercontent.com/16472853/171686035-2ef7c3b2-a100-4d45-a57a-65d4f915884a.png)

**Comment by tulir** [comment]
Threads are already bridged as native Matrix threads
