### ISSUE TITLE
Login Link Broken 404 Error

### ISSUE THREAD

**Issue by maxlahn** [mautrix/googlechat#85]
Just set up a new installation of the bridge in docker according to the instructions at https://docs.mau.fi/bridges/general/docker-setup.html?bridge=googlechat. I can see that my homeserver and the bridge are communicating fine, both from the logs and from the fact that the bridge bot is responsive in direct messages.

However, when I try to log into my Gmail account by the login command, the link provided in step 1 returns a 404 error. Is it possible that Google changed the syntax for registering a new device, and that's why login isn't working?

**Comment by adamshand** [comment]
I'm seeing the same thing.  Fresh install of GoogleChat bridge generates this link:

```
https://accounts.google.com/o/oauth2/programmatic_auth?scope=https%3A%2F%2Fwww.google.com%2Faccounts%2FOAuthLogin+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email&client_id=xxxxxx.apps.googleusercontent.com&device_name=Mautrix-Google+Chat+bridge
```

**Comment by barto95100** [comment]
The same problème and the result on page is broken 404 not found

**Comment by lrcilento** [comment]
I'm having the same issue...

**Comment by iFargle** [comment]
https://github.com/mautrix/googlechat/blob/21b96172e3cc0d31eabd444e1cdad8f548070bf9/maugclib/auth.py#L34

I'm guessing this expired

**Comment by barto95100** [comment]
YEs but the url generate is not good maybe

**Comment by timaeos** [comment]
Appears that this might be related to google enforcing the `redirect_uri` policy to not allow domains with `googleusercontent.com` as the domain. [uri validation requirements](https://developers.google.com/identity/protocols/oauth2/web-server#uri-validation)

or maybe the link is just malformed. 

I'm not sure which but I assume tulir already knows about it to some extent. Will just wait patiently for now and perhaps make sure people that are already logged in don't log out of their bridges.

**Comment by amstan** [comment]
There's a new branch where tulir seems to be working in this area, https://github.com/mautrix/googlechat/compare/master...authadvice

I tried it, but didn't have much success (error 400), despite executing the funky "pretend to be an ios user agent" instructions.

**Comment by ljlongwing** [comment]
On Aug 2016 this post (https://developers.googleblog.com/2016/08/modernizing-oauth-interactions-in-native-apps.html) says that the URL format
"https://accounts.google.com/o/oauth2/programmatic_auth"
was being deprecated and needs to be replaced....looks like this bridge is still using it....maybe 6.5 years later they decided to turn it off?

**Comment by VisitingOcean** [comment]
@tulir is authadvice the current branch for this fix? Need help?

**Comment by bramenn** [comment]
This is an interesting challenge

**Comment by gravityfargo** [comment]
On desktop chrome I get the message 

> 404. That’s an error.
> The requested URL was not found on this server. That’s all we know.

on chrome android I get

> null. That's an error. 
> com.google.iso.protocol.oauth2.common.validation.ValidationException: Mismatched device type. That’s all we know.
