### ISSUE TITLE
How to bulk delete messages on Google Chat Space?

### ISSUE THREAD

**Issue by Derpitron** [mautrix/googlechat#94]
I am using the [Beeper](https://www.beeper.com/) Matrix-GChat client and bridge. The Beeper client provides a "Send Custom Event" feature which lets me apparently send my own custom APi requests? (Not sure of this).

![image](https://github.com/mautrix/googlechat/assets/46134462/7f4782ba-85f4-46b7-8b9a-f83fd96bc6f3)

I would like to know how to:
1. Iterate through all messages with Me as the author in a Google Chat Space
2. Send "redaction"/"removal"/"deletion" for each message

**Comment by sumnerevans** [comment]
First, why? What are you trying to accomplish by deleting everything (that could have an affect on the answer)?

Second, you will have to use the [matrix client-server API](https://spec.matrix.org/v1.7/client-server-api/) to do this. That dialog is only for sending matrix events, not calling every API endpoint.

The issue tracker is not the correct place for discussing this as it is not a bug in the bridge. You'll probably find better help if you discuss in [#:maunium.net](https://matrix.to/#/#:maunium.net) or possibly [#googlechat:maunium.net](https://matrix.to/#/#googlechat:maunium.net)

**Comment by Derpitron** [comment]
> The issue tracker is not the correct place for discussing this as it is not a bug in the bridge. You'll probably find better help if you discuss in [#:maunium.net](https://matrix.to/#/#:maunium.net) or possibly [#googlechat:maunium.net](https://matrix.to/#/#googlechat:maunium.net)

Thanks for the matrix room link. I'll try asking there. Apologies for the wasteful issue!
