### ISSUE TITLE
"Those cookies don't seem to be valid"

### ISSUE THREAD

**Issue by CyberShadow** [mautrix/googlechat#96]
I've set up the bridge some time ago, and it worked until some point.

Today, I can't log in. Following the instructions gives me "Those cookies don't seem to be valid".

Also, I notice that the `COMPASS` cookie no longer starts with `dynamite-ui=`, it now starts with `gmail_chat=`.

Thanks!

**Comment by junetried** [comment]
I think you're looking at the cookies for `mail.google.com`? Try `chat.google.com` instead.

**Comment by CyberShadow** [comment]
I tried following the instructions today and it worked, so you're probably right. Thanks!
