### ISSUE TITLE
Cannot write to channel

### ISSUE THREAD

**Issue by d4g** [mautrix/googlechat#97]
When I try to write to a channel, I receive the following error:
`⚠ Your message may not have been bridged: Request return unexpected status: 400: Bad Request `

I still receive new messages though.

Version: 0.5

**Comment by tulir** [comment]
That happens on some old versions of the bridge if it's running for more than 2 weeks without being restarted

**Comment by d4g** [comment]
Version 0.5 is the latest release right?

**Comment by sumnerevans** [comment]
[v0.5.1](https://github.com/mautrix/googlechat/releases/tag/v0.5.1) is latest now

**Comment by d4g** [comment]
Strange - after a reboot the bridge wants me to login again. Before the reboot it just didn't work right, throwing those Error 400.
